### ISSUE TITLE
add expandable window for inter-game navigation.

### ISSUE THREAD

**Issue by pickled-dev** [pickled-dev/smt-tools#45]
I'm not happy with the tabs at the top because they take up so much space and are unusable on mobile. The answer is probably to have an button in the top-left that pulls out a window with each game on a grid. Like what github has at the time of writing. Click a button in the top left of the site, then get a window expand from the left bunch of navigation links. For me it would probably be a grid of every game's logo.

**Comment by PickleProgramming** [comment]
Thankfully, this is a common use case and Material already has it all setup for me. 

Angular Material SideNav:
https://material.angular.io/components/sidenav/overview

Example:
https://stackblitz.com/run?file=package.json

Of course, this implementation will lack the style and flair of Persona 5 menu, but I think for the moment custom animations like that are out of my reach.

**Comment by pickled-dev** [comment]
resolved with 8864cbffda68bdd277dad1089f024bf1516799fa
